name: TRLC CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:

  lint:
    name: PyLint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint pycodestyle
          python -m pip install --no-deps bmw-lobster-core bmw-lobster-tool-trlc
      - name: Style check
        run: |
          make style
      - name: Lint
        run: |
          make lint -o style

  test:
    name: Test
    strategy:
      matrix:
        py-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: supplypike/setup-bin@v4
        with:
          uri: 'https://github.com/cvc5/cvc5/releases/download/cvc5-1.0.8/cvc5-Linux'
          name: 'cvc5'
          version: '1.0.8'
      - name: Set up Python ${{ matrix.py-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Executing system tests
        run: |
          make system-tests
      - name: Executing unit tests
        run: |
          make unit-tests
      - name: Coverage analysis
        run: |
          make coverage -o system-tests -o unit-tests
      - name: Test status
        run: |
          util/check_local_modifications.sh
